# Data Preprocessing Method

## Step 1: Import required libraries

In [78]:
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

## Step 2: Load the dataset

In [80]:
df = pd.read_csv("PhD_Dataset_Incidence.csv")

# View first 5 rows
df.head()

,hh,sex,age,lga,edu,mrt_status,fmly_size,m_income,cfuel,ipollut,...,h_facility,dist_hfacility,illiness,waterborne,resp_disease,eye_disease,child_death,maternalcare,square_meal,health_ins
0,1.0,1,3.0,1,6,1,4,4,6,1,...,1.0,1.0,2.0,0,0.0,0,0,2.0,3.0,1.0
1,2.0,1,3.0,1,7,1,7,7,6,1,...,1.0,0.5,5.0,2,0.0,0,0,2.0,3.0,1.0
2,3.0,1,3.0,1,6,1,5,5,6,1,...,1.0,0.5,2.0,0,0.0,0,0,2.0,3.0,1.0
3,4.0,1,3.0,1,6,1,6,3,6,1,...,1.0,0.5,4.0,0,0.0,0,2,2.0,2.0,1.0
4,5.0,1,4.0,1,5,1,10,7,6,1,...,1.0,3.0,10.0,2,0.0,0,0,1.0,3.0,1.0

## Step 3: Check number of rows and columns

In [82]:
df.shape

(499, 52)

## Step 4: View all column names

In [84]:
df.columns

Index(['hh', 'sex', 'age', 'lga', 'edu', 'mrt_status', 'fmly_size', 'm_income',
       'cfuel', 'ipollut', 'rbiomass', 'dailycook', 'avl_lpg', 'aff_lpg',
       'Electricity', 'hrs_elect', 'aff_elct', 'exp_elct', 'source_light',
       'exp_lpg', 'exp_nonlpg', 'aff_solide', 'hh_appl', 'edu_appl', 'c_appl',
       'occupation', 'hh_exp', 'housing', 'wall', 'floor', 'rooms', 'bank',
       'bank_acct', 'b_facility', 'road', 'raod_dist', 'schl', 'type_sch',
       'dst_sch', 'sch_days', 'sch_drpout', 'chld_labor', 'h_facility',
       'dist_hfacility', 'illiness', 'waterborne', 'resp_disease',
       'eye_disease', 'child_death', 'maternalcare', 'square_meal',
       'health_ins'],
      dtype='object')

## Step 5: Check data types and missing values

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 52 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hh              167 non-null    float64
 1   sex             499 non-null    int64
 2   age             497 non-null    float64
 3   lga             499 non-null    int64
 4   edu             499 non-null    int64
 5   mrt_status      499 non-null    int64
 6   fmly_size       499 non-null    int64
 7   m_income        499 non-null    int64
 8   cfuel           499 non-null    int64
 9   ipollut         499 non-null    int64
 10  rbiomass        374 non-null    float64
 11  dailycook       497 non-null    float64
 12  avl_lpg         499 non-null    int64
 13  aff_lpg         499 non-null    int64
 14  Electricity     497 non-null    float64
 15  hrs_elect       499 non-null    float64
 16  aff_elct        485 non-null    float64
 17  exp_elct        499 non-null    object
 18  source_light    441 non-null    float64
 19  exp_lpg         499 non-null    object
 20  exp_nonlpg      499 non-null    object
 21  aff_solide      499 non-null    int64
 22  hh_appl         499 non-null    int64
 23  edu_appl        499 non-null    int64
 24  c_appl          499 non-null    int64
 25  occupation      499 non-null    int64
 26  hh_exp          466 non-null    object
 27  housing         491 non-null    float64
 28  wall            475 non-null    float64
 29  floor           484 non-null    float64
 30  rooms           484 non-null    float64
 31  bank            495 non-null    float64
 32  bank_acct       498 non-null    float64
 33  b_facility      494 non-null    float64
 34  road            486 non-null    float64
 35  raod_dist       499 non-null    int64
 36  schl            499 non-null    int64
 37  type_sch        488 non-null    float64
 38  dst_sch         456 non-null    object
 39  sch_days        499 non-null    int64
 40  sch_drpout      499 non-null    int64
 41  chld_labor      498 non-null    float64
 42  h_facility      493 non-null    float64
 43  dist_hfacility  464 non-null    float64
 44  illiness        494 non-null    float64
 45  waterborne      499 non-null    int64
 46  resp_disease    498 non-null    float64
 47  eye_disease     499 non-null    int64
 48  child_death     499 non-null    int64
 49  maternalcare    486 non-null    float64
 50  square_meal     471 non-null    float64
 51  health_ins      498 non-null    float64
dtypes: float64(25), int64(22), object(5)
memory usage: 202.8+ KB

## Step 6: Remove commas from numeric values

In [70]:
df = df.replace(',', '', regex=True)

# Convert numeric columns safely
for col in df.columns:
    try:
        df[col] = pd.to_numeric(df[col])
    except:
        pass

# Fill missing values
df.fillna(df.median(numeric_only=True), inplace=True)

# Check dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 52 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hh              499 non-null    float64
 1   sex             499 non-null    int64
 2   age             499 non-null    float64
 3   lga             499 non-null    int64
 4   edu             499 non-null    int64
 5   mrt_status      499 non-null    int64
 6   fmly_size       499 non-null    int64
 7   m_income        499 non-null    int64
 8   cfuel           499 non-null    int64
 9   ipollut         499 non-null    int64
 10  rbiomass        499 non-null    float64
 11  dailycook       499 non-null    float64
 12  avl_lpg         499 non-null    int64
 13  aff_lpg         499 non-null    int64
 14  Electricity     499 non-null    float64
 15  hrs_elect       499 non-null    float64
 16  aff_elct        499 non-null    float64
 17  exp_elct        499 non-null    int64
 18  source_light    499 non-null    float64
 19  exp_lpg         499 non-null    int64
 20  exp_nonlpg      499 non-null    int64
 21  aff_solide      499 non-null    int64
 22  hh_appl         499 non-null    int64
 23  edu_appl        499 non-null    int64
 24  c_appl          499 non-null    int64
 25  occupation      499 non-null    int64
 26  hh_exp          499 non-null    float64
 27  housing         499 non-null    float64
 28  wall            499 non-null    float64
 29  floor           499 non-null    float64
 30  rooms           499 non-null    float64
 31  bank            499 non-null    float64
 32  bank_acct       499 non-null    float64
 33  b_facility      499 non-null    float64
 34  road            499 non-null    float64
 35  raod_dist       499 non-null    int64
 36  schl            499 non-null    int64
 37  type_sch        499 non-null    float64
 38  dst_sch         456 non-null    object
 39  sch_days        499 non-null    int64
 40  sch_drpout      499 non-null    int64
 41  chld_labor      499 non-null    float64
 42  h_facility      499 non-null    float64
 43  dist_hfacility  499 non-null    float64
 44  illiness        499 non-null    float64
 45  waterborne      499 non-null    int64
 46  resp_disease    499 non-null    float64
 47  eye_disease     499 non-null    int64
 48  child_death     499 non-null    int64
 49  maternalcare    499 non-null    float64
 50  square_meal     499 non-null    float64
 51  health_ins      499 non-null    float64
dtypes: float64(26), int64(25), object(1)
memory usage: 202.8+ KB

## Step 7: Remove duplicate rows

In [88]:
df = df.drop_duplicates()

df.shape

(499, 52)

## Step 8: Statistical summary

In [90]:
df.describe()

,hh,sex,age,lga,edu,mrt_status,fmly_size,m_income,cfuel,ipollut,...,h_facility,dist_hfacility,illiness,waterborne,resp_disease,eye_disease,child_death,maternalcare,square_meal,health_ins
count,167.000000,499.000000,497.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,...,493.00000,464.000000,494.000000,499.000000,498.000000,499.000000,499.000000,486.000000,471.000000,498.000000
mean,84.059880,1.036072,3.519115,3.468938,3.416834,1.472946,8.665331,2.869739,3.649299,1.404810,...,1.03854,1.445582,3.601215,2.068136,0.441767,0.661323,1.354709,1.450617,2.819533,1.628514
std,48.284261,0.186657,1.236270,1.868288,1.604023,1.062679,5.501572,1.734676,1.429485,0.491348,...,0.19269,1.623483,2.588177,2.366807,1.194228,1.313938,1.707658,0.498068,0.521170,0.483688
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.00000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,42.500000,1.000000,3.000000,2.000000,2.000000,1.000000,5.000000,2.000000,3.000000,1.000000,...,1.00000,0.500000,2.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,1.000000
50%,84.000000,1.000000,3.000000,4.000000,3.000000,1.000000,7.000000,2.000000,3.000000,1.000000,...,1.00000,1.000000,3.000000,1.000000,0.000000,0.000000,1.000000,1.000000,3.000000,2.000000
75%,125.500000,1.000000,4.000000,5.000000,5.000000,1.000000,11.000000,4.000000,4.000000,2.000000,...,1.00000,1.500000,5.000000,3.000000,0.000000,1.000000,2.000000,2.000000,3.000000,2.000000
max,167.000000,2.000000,6.000000,6.000000,7.000000,4.000000,40.000000,7.000000,7.000000,2.000000,...,2.00000,15.000000,15.000000,15.000000,10.000000,12.000000,15.000000,2.000000,6.000000,2.000000

## Step 9: Create Energy Poverty target variable

In [92]:
df['energy_poor'] = np.where(
    (df['Electricity'] == 0) | (df['hrs_elect'] < 6) | (df['cfuel'] == 3),
    1, 0
)

df['energy_poor'].value_counts()

energy_poor
1    395
0    104
Name: count, dtype: int64