# Data Preprocessing Method-(Ashish)

## Step 1: Import Required Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Step 2: Load the dataset

In [2]:
dataset=pd.read_csv("PhD_Dataset_Incidence.csv")
dataset

,hh,sex,age,lga,edu,mrt_status,fmly_size,m_income,cfuel,ipollut,...,h_facility,dist_hfacility,illiness,waterborne,resp_disease,eye_disease,child_death,maternalcare,square_meal,health_ins
0,1.0,1,3.0,1,6,1,4,4,6,1,...,1.0,1.0,2.0,0,0.0,0,0,2.0,3.0,1.0
1,2.0,1,3.0,1,7,1,7,7,6,1,...,1.0,0.5,5.0,2,0.0,0,0,2.0,3.0,1.0
2,3.0,1,3.0,1,6,1,5,5,6,1,...,1.0,0.5,2.0,0,0.0,0,0,2.0,3.0,1.0
3,4.0,1,3.0,1,6,1,6,3,6,1,...,1.0,0.5,4.0,0,0.0,0,2,2.0,2.0,1.0
4,5.0,1,4.0,1,5,1,10,7,6,1,...,1.0,3.0,10.0,2,0.0,0,0,1.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,NaN,2,2.0,5,2,2,5,1,4,1,...,1.0,10.0,2.0,1,0.0,0,0,NaN,2.0,2.0
495,NaN,1,2.0,5,6,4,5,4,6,1,...,1.0,1.0,2.0,0,0.0,0,0,NaN,3.0,2.0
496,NaN,1,3.0,5,5,4,4,3,7,1,...,1.0,4.0,0.0,0,0.0,0,0,2.0,3.0,1.0
497,NaN,1,3.0,5,3,1,4,2,4,2,...,1.0,1.0,4.0,2,0.0,2,0,1.0,NaN,2.0
498,NaN,1,3.0,5,4,1,5,2,3,2,...,1.0,1.0,4.0,4,0.0,0,1,1.0,3.0,1.0

## Step 3: Lower Feature

In [5]:
dataset.columns=dataset.columns.str.lower()
dataset

,hh,sex,age,lga,edu,mrt_status,fmly_size,m_income,cfuel,ipollut,...,h_facility,dist_hfacility,illiness,waterborne,resp_disease,eye_disease,child_death,maternalcare,square_meal,health_ins
0,1.0,1,3.0,1,6,1,4,4,6,1,...,1.0,1.0,2.0,0,0.0,0,0,2.0,3.0,1.0
1,2.0,1,3.0,1,7,1,7,7,6,1,...,1.0,0.5,5.0,2,0.0,0,0,2.0,3.0,1.0
2,3.0,1,3.0,1,6,1,5,5,6,1,...,1.0,0.5,2.0,0,0.0,0,0,2.0,3.0,1.0
3,4.0,1,3.0,1,6,1,6,3,6,1,...,1.0,0.5,4.0,0,0.0,0,2,2.0,2.0,1.0
4,5.0,1,4.0,1,5,1,10,7,6,1,...,1.0,3.0,10.0,2,0.0,0,0,1.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,NaN,2,2.0,5,2,2,5,1,4,1,...,1.0,10.0,2.0,1,0.0,0,0,NaN,2.0,2.0
495,NaN,1,2.0,5,6,4,5,4,6,1,...,1.0,1.0,2.0,0,0.0,0,0,NaN,3.0,2.0
496,NaN,1,3.0,5,5,4,4,3,7,1,...,1.0,4.0,0.0,0,0.0,0,0,2.0,3.0,1.0
497,NaN,1,3.0,5,3,1,4,2,4,2,...,1.0,1.0,4.0,2,0.0,2,0,1.0,NaN,2.0
498,NaN,1,3.0,5,4,1,5,2,3,2,...,1.0,1.0,4.0,4,0.0,0,1,1.0,3.0,1.0

## Step 4: Correction of Datatypes

In [7]:
dataset.dtypes

hh                float64
sex                 int64
age               float64
lga                 int64
edu                 int64
mrt_status          int64
fmly_size           int64
m_income            int64
cfuel               int64
ipollut             int64
rbiomass          float64
dailycook         float64
avl_lpg             int64
aff_lpg             int64
electricity       float64
hrs_elect         float64
aff_elct          float64
exp_elct           object
source_light      float64
exp_lpg            object
exp_nonlpg         object
aff_solide          int64
hh_appl             int64
edu_appl            int64
c_appl              int64
occupation          int64
hh_exp             object
housing           float64
wall              float64
floor             float64
rooms             float64
bank              float64
bank_acct         float64
b_facility        float64
road              float64
raod_dist           int64
schl                int64
type_sch          float64
dst_sch            object
sch_days            int64
sch_drpout          int64
chld_labor        float64
h_facility        float64
dist_hfacility    float64
illiness          float64
waterborne          int64
resp_disease      float64
eye_disease         int64
child_death         int64
maternalcare      float64
square_meal       float64
health_ins        float64
dtype: object

In [9]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 52 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hh              167 non-null    float64
 1   sex             499 non-null    int64
 2   age             497 non-null    float64
 3   lga             499 non-null    int64
 4   edu             499 non-null    int64
 5   mrt_status      499 non-null    int64
 6   fmly_size       499 non-null    int64
 7   m_income        499 non-null    int64
 8   cfuel           499 non-null    int64
 9   ipollut         499 non-null    int64
 10  rbiomass        374 non-null    float64
 11  dailycook       497 non-null    float64
 12  avl_lpg         499 non-null    int64
 13  aff_lpg         499 non-null    int64
 14  electricity     497 non-null    float64
 15  hrs_elect       499 non-null    float64
 16  aff_elct        485 non-null    float64
 17  exp_elct        499 non-null    object
 18  source_light    441 non-null    float64
 19  exp_lpg         499 non-null    object
 20  exp_nonlpg      499 non-null    object
 21  aff_solide      499 non-null    int64
 22  hh_appl         499 non-null    int64
 23  edu_appl        499 non-null    int64
 24  c_appl          499 non-null    int64
 25  occupation      499 non-null    int64
 26  hh_exp          466 non-null    object
 27  housing         491 non-null    float64
 28  wall            475 non-null    float64
 29  floor           484 non-null    float64
 30  rooms           484 non-null    float64
 31  bank            495 non-null    float64
 32  bank_acct       498 non-null    float64
 33  b_facility      494 non-null    float64
 34  road            486 non-null    float64
 35  raod_dist       499 non-null    int64
 36  schl            499 non-null    int64
 37  type_sch        488 non-null    float64
 38  dst_sch         456 non-null    object
 39  sch_days        499 non-null    int64
 40  sch_drpout      499 non-null    int64
 41  chld_labor      498 non-null    float64
 42  h_facility      493 non-null    float64
 43  dist_hfacility  464 non-null    float64
 44  illiness        494 non-null    float64
 45  waterborne      499 non-null    int64
 46  resp_disease    498 non-null    float64
 47  eye_disease     499 non-null    int64
 48  child_death     499 non-null    int64
 49  maternalcare    486 non-null    float64
 50  square_meal     471 non-null    float64
 51  health_ins      498 non-null    float64
dtypes: float64(25), int64(22), object(5)
memory usage: 202.8+ KB

In [11]:
dataset['hh']=dataset['hh'].fillna(0).astype(int)
dataset['m_income']=dataset['m_income'].astype(float)
dataset['cfuel']=dataset['cfuel'].astype('category')
dataset['electricity']=dataset['electricity'].astype('category')

In [13]:
dataset['m_income']=pd.to_numeric(dataset['m_income'],errors='coerce')

In [15]:
print(dataset.dtypes)

hh                   int32
sex                  int64
age                float64
lga                  int64
edu                  int64
mrt_status           int64
fmly_size            int64
m_income           float64
cfuel             category
ipollut              int64
rbiomass           float64
dailycook          float64
avl_lpg              int64
aff_lpg              int64
electricity       category
hrs_elect          float64
aff_elct           float64
exp_elct            object
source_light       float64
exp_lpg             object
exp_nonlpg          object
aff_solide           int64
hh_appl              int64
edu_appl             int64
c_appl               int64
occupation           int64
hh_exp              object
housing            float64
wall               float64
floor              float64
rooms              float64
bank               float64
bank_acct          float64
b_facility         float64
road               float64
raod_dist            int64
schl                 int64
type_sch           float64
dst_sch             object
sch_days             int64
sch_drpout           int64
chld_labor         float64
h_facility         float64
dist_hfacility     float64
illiness           float64
waterborne           int64
resp_disease       float64
eye_disease          int64
child_death          int64
maternalcare       float64
square_meal        float64
health_ins         float64
dtype: object

# Data Preprocessing Method-(Sabari)

## Step 1: Import required libraries

In [17]:
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

## Step 2: Load the dataset

In [19]:
df = pd.read_csv("PhD_Dataset_Incidence.csv")

# View first 5 rows
df.head()

,hh,sex,age,lga,edu,mrt_status,fmly_size,m_income,cfuel,ipollut,...,h_facility,dist_hfacility,illiness,waterborne,resp_disease,eye_disease,child_death,maternalcare,square_meal,health_ins
0,1.0,1,3.0,1,6,1,4,4,6,1,...,1.0,1.0,2.0,0,0.0,0,0,2.0,3.0,1.0
1,2.0,1,3.0,1,7,1,7,7,6,1,...,1.0,0.5,5.0,2,0.0,0,0,2.0,3.0,1.0
2,3.0,1,3.0,1,6,1,5,5,6,1,...,1.0,0.5,2.0,0,0.0,0,0,2.0,3.0,1.0
3,4.0,1,3.0,1,6,1,6,3,6,1,...,1.0,0.5,4.0,0,0.0,0,2,2.0,2.0,1.0
4,5.0,1,4.0,1,5,1,10,7,6,1,...,1.0,3.0,10.0,2,0.0,0,0,1.0,3.0,1.0

## Step 3: Check number of rows and columns

In [ ]:
df.shape

(499, 52)

## Step 4: View all column names

In [ ]:
df.columns

Index(['hh', 'sex', 'age', 'lga', 'edu', 'mrt_status', 'fmly_size', 'm_income',
       'cfuel', 'ipollut', 'rbiomass', 'dailycook', 'avl_lpg', 'aff_lpg',
       'Electricity', 'hrs_elect', 'aff_elct', 'exp_elct', 'source_light',
       'exp_lpg', 'exp_nonlpg', 'aff_solide', 'hh_appl', 'edu_appl', 'c_appl',
       'occupation', 'hh_exp', 'housing', 'wall', 'floor', 'rooms', 'bank',
       'bank_acct', 'b_facility', 'road', 'raod_dist', 'schl', 'type_sch',
       'dst_sch', 'sch_days', 'sch_drpout', 'chld_labor', 'h_facility',
       'dist_hfacility', 'illiness', 'waterborne', 'resp_disease',
       'eye_disease', 'child_death', 'maternalcare', 'square_meal',
       'health_ins'],
      dtype='object')

## Step 5: Check data types and missing values

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 52 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hh              167 non-null    float64
 1   sex             499 non-null    int64
 2   age             497 non-null    float64
 3   lga             499 non-null    int64
 4   edu             499 non-null    int64
 5   mrt_status      499 non-null    int64
 6   fmly_size       499 non-null    int64
 7   m_income        499 non-null    int64
 8   cfuel           499 non-null    int64
 9   ipollut         499 non-null    int64
 10  rbiomass        374 non-null    float64
 11  dailycook       497 non-null    float64
 12  avl_lpg         499 non-null    int64
 13  aff_lpg         499 non-null    int64
 14  Electricity     497 non-null    float64
 15  hrs_elect       499 non-null    float64
 16  aff_elct        485 non-null    float64
 17  exp_elct        499 non-null    object
 18  source_light    441 non-null    float64
 19  exp_lpg         499 non-null    object
 20  exp_nonlpg      499 non-null    object
 21  aff_solide      499 non-null    int64
 22  hh_appl         499 non-null    int64
 23  edu_appl        499 non-null    int64
 24  c_appl          499 non-null    int64
 25  occupation      499 non-null    int64
 26  hh_exp          466 non-null    object
 27  housing         491 non-null    float64
 28  wall            475 non-null    float64
 29  floor           484 non-null    float64
 30  rooms           484 non-null    float64
 31  bank            495 non-null    float64
 32  bank_acct       498 non-null    float64
 33  b_facility      494 non-null    float64
 34  road            486 non-null    float64
 35  raod_dist       499 non-null    int64
 36  schl            499 non-null    int64
 37  type_sch        488 non-null    float64
 38  dst_sch         456 non-null    object
 39  sch_days        499 non-null    int64
 40  sch_drpout      499 non-null    int64
 41  chld_labor      498 non-null    float64
 42  h_facility      493 non-null    float64
 43  dist_hfacility  464 non-null    float64
 44  illiness        494 non-null    float64
 45  waterborne      499 non-null    int64
 46  resp_disease    498 non-null    float64
 47  eye_disease     499 non-null    int64
 48  child_death     499 non-null    int64
 49  maternalcare    486 non-null    float64
 50  square_meal     471 non-null    float64
 51  health_ins      498 non-null    float64
dtypes: float64(25), int64(22), object(5)
memory usage: 202.8+ KB

## Step 6: Remove commas from numeric values

In [ ]:
df = df.replace(',', '', regex=True)

# Convert numeric columns safely
for col in df.columns:
    try:
        df[col] = pd.to_numeric(df[col])
    except:
        pass

# Fill missing values
df.fillna(df.median(numeric_only=True), inplace=True)

# Check dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 52 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hh              499 non-null    float64
 1   sex             499 non-null    int64
 2   age             499 non-null    float64
 3   lga             499 non-null    int64
 4   edu             499 non-null    int64
 5   mrt_status      499 non-null    int64
 6   fmly_size       499 non-null    int64
 7   m_income        499 non-null    int64
 8   cfuel           499 non-null    int64
 9   ipollut         499 non-null    int64
 10  rbiomass        499 non-null    float64
 11  dailycook       499 non-null    float64
 12  avl_lpg         499 non-null    int64
 13  aff_lpg         499 non-null    int64
 14  Electricity     499 non-null    float64
 15  hrs_elect       499 non-null    float64
 16  aff_elct        499 non-null    float64
 17  exp_elct        499 non-null    int64
 18  source_light    499 non-null    float64
 19  exp_lpg         499 non-null    int64
 20  exp_nonlpg      499 non-null    int64
 21  aff_solide      499 non-null    int64
 22  hh_appl         499 non-null    int64
 23  edu_appl        499 non-null    int64
 24  c_appl          499 non-null    int64
 25  occupation      499 non-null    int64
 26  hh_exp          499 non-null    float64
 27  housing         499 non-null    float64
 28  wall            499 non-null    float64
 29  floor           499 non-null    float64
 30  rooms           499 non-null    float64
 31  bank            499 non-null    float64
 32  bank_acct       499 non-null    float64
 33  b_facility      499 non-null    float64
 34  road            499 non-null    float64
 35  raod_dist       499 non-null    int64
 36  schl            499 non-null    int64
 37  type_sch        499 non-null    float64
 38  dst_sch         456 non-null    object
 39  sch_days        499 non-null    int64
 40  sch_drpout      499 non-null    int64
 41  chld_labor      499 non-null    float64
 42  h_facility      499 non-null    float64
 43  dist_hfacility  499 non-null    float64
 44  illiness        499 non-null    float64
 45  waterborne      499 non-null    int64
 46  resp_disease    499 non-null    float64
 47  eye_disease     499 non-null    int64
 48  child_death     499 non-null    int64
 49  maternalcare    499 non-null    float64
 50  square_meal     499 non-null    float64
 51  health_ins      499 non-null    float64
dtypes: float64(26), int64(25), object(1)
memory usage: 202.8+ KB

## Step 7: Remove duplicate rows

In [ ]:
df = df.drop_duplicates()

df.shape

(499, 52)

## Step 8: Statistical summary

In [ ]:
df.describe()

,hh,sex,age,lga,edu,mrt_status,fmly_size,m_income,cfuel,ipollut,...,h_facility,dist_hfacility,illiness,waterborne,resp_disease,eye_disease,child_death,maternalcare,square_meal,health_ins
count,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,...,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000
mean,84.020040,1.036072,3.517034,3.468938,3.416834,1.472946,8.665331,2.869739,3.649299,1.404810,...,1.038076,1.414329,3.595190,2.068136,0.440882,0.661323,1.354709,1.438878,2.829659,1.629259
std,27.876946,0.186657,1.234222,1.868288,1.604023,1.062679,5.501572,1.734676,1.429485,0.491348,...,0.191572,1.569533,2.575849,2.366807,1.193192,1.313938,1.707658,0.496748,0.508010,0.483488
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,84.000000,1.000000,3.000000,2.000000,2.000000,1.000000,5.000000,2.000000,3.000000,1.000000,...,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,1.000000
50%,84.000000,1.000000,3.000000,4.000000,3.000000,1.000000,7.000000,2.000000,3.000000,1.000000,...,1.000000,1.000000,3.000000,1.000000,0.000000,0.000000,1.000000,1.000000,3.000000,2.000000
75%,84.000000,1.000000,4.000000,5.000000,5.000000,1.000000,11.000000,4.000000,4.000000,2.000000,...,1.000000,1.200000,5.000000,3.000000,0.000000,1.000000,2.000000,2.000000,3.000000,2.000000
max,167.000000,2.000000,6.000000,6.000000,7.000000,4.000000,40.000000,7.000000,7.000000,2.000000,...,2.000000,15.000000,15.000000,15.000000,10.000000,12.000000,15.000000,2.000000,6.000000,2.000000

## Step 9: Create Energy Poverty target variable

In [ ]:
df['energy_poor'] = np.where(
    (df['Electricity'] == 0) | (df['hrs_elect'] < 6) | (df['cfuel'] == 3),
    1, 0
)

df['energy_poor'].value_counts()

energy_poor
1    395
0    104
Name: count, dtype: int64

### Data Preprocessing by Ashish was
-Import the libraries, Load the dataset, lower feature title, Correction of datatypes.

### Data Preprocessing by Sabari was
- Import required libraries, Load the dataset, Check number of rows and columns, View all column names, Check data types and missing values, Remove commas from numeric values, Remove duplicate rows, Statistical summary, Create Energy Poverty target variable.

In [ ]:
# Feature Extraction - Member 1 (Energy Access Features)

In [21]:
df.head()
df.columns

Index(['hh', 'sex', 'age', 'lga', 'edu', 'mrt_status', 'fmly_size', 'm_income',
       'cfuel', 'ipollut', 'rbiomass', 'dailycook', 'avl_lpg', 'aff_lpg',
       'Electricity', 'hrs_elect', 'aff_elct', 'exp_elct', 'source_light',
       'exp_lpg', 'exp_nonlpg', 'aff_solide', 'hh_appl', 'edu_appl', 'c_appl',
       'occupation', 'hh_exp', 'housing', 'wall', 'floor', 'rooms', 'bank',
       'bank_acct', 'b_facility', 'road', 'raod_dist', 'schl', 'type_sch',
       'dst_sch', 'sch_days', 'sch_drpout', 'chld_labor', 'h_facility',
       'dist_hfacility', 'illiness', 'waterborne', 'resp_disease',
       'eye_disease', 'child_death', 'maternalcare', 'square_meal',
       'health_ins'],
      dtype='object')

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_excel("PhD_Dataset_Incidence.xlsx")

In [ ]:
df.head()
df.columns

Index(['hh', 'sex', 'age', 'lga', 'edu', 'mrt_status', 'fmly_size', 'm_income',
       'cfuel', 'ipollut', 'rbiomass', 'dailycook', 'avl_lpg', 'aff_lpg',
       'Electricity', 'hrs_elect', 'aff_elct', 'exp_elct', 'source_light',
       'exp_lpg', 'exp_nonlpg', 'aff_solide', 'hh_appl', 'edu_appl', 'c_appl',
       'occupation', 'hh_exp', 'housing', 'wall', 'floor', 'rooms', 'bank',
       'bank_acct', 'b_facility', 'road', 'raod_dist', 'schl', 'type_sch',
       'dst_sch', 'sch_days', 'sch_drpout', 'chld_labor', 'h_facility',
       'dist_hfacility', 'illiness', 'waterborne', 'resp_disease',
       'eye_disease', 'child_death', 'maternalcare', 'square_meal',
       'health_ins'],
      dtype='object')

In [16]:
df['energy_income_ratio'] = df['exp_elct'] / (df['m_income'] + 1)

In [15]:
df['electricity_sufficient'] = (df['hrs_elect'] >= 12).astype(int)

In [17]:
df['electricity_score'] = df['Electricity'] * df['hrs_elect']

In [18]:
df['energy_burden'] = df['exp_elct'] / (df['m_income'] + 1)

In [19]:
df[['energy_income_ratio','electricity_sufficient','electricity_score','energy_burden']].head()

,energy_income_ratio,electricity_sufficient,electricity_score,energy_burden
0,2000.000000,1,12.0,2000.000000
1,1250.000000,0,8.0,1250.000000
2,333.333333,0,4.0,333.333333
3,1250.000000,1,16.0,1250.000000
4,1250.000000,0,5.0,1250.000000

## feature Extraction part 2

In [62]:
df['rooms_per_person'] = df['rooms'] / (df['fmly_size'] + 1)

In [64]:
df['people_per_room'] = df[ 'fmly_size'] / (df['rooms'] + 1)

In [66]:
df['rooms_per_person'] = df['rooms'] / (df['fmly_size'] + 1)

In [68]:
df['people_per_room'] = df[ 'fmly_size'] / (df['rooms'] + 1)

In [70]:
df.to_csv("Cleaned_dataset_energy_poverty.csv", index=False)

In [72]:
df.to_csv("Cleaned_dataset_energy_poverty.csv", index=False)
print("Dataset saved successfully")

Dataset saved successfully

## Cleaned Data energy poverty

In [80]:
df.to_csv(r"C:\Users\admin\Desktop\Cleaned_dataset_energy_poverty.csv", index=False)